In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset("titanic")

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
df.drop(["deck", "alive", "class", "who", "adult_male", "embark_town"], axis=1, inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [8]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["embarked"].fillna(df["embarked"].mode()[0], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  891 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [9]:
# Import LabelEncoder from sklearn
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
le = LabelEncoder()

In [10]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [11]:
df=df.astype(int)

In [12]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [13]:
# Separate features (X) and target (y)

# Drop 'survived' column from dataset → this becomes input features
X = df.drop("survived", axis=1)

# Select 'survived' column → this is the target variable
y = df["survived"]


# Import function to split dataset
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,      # 20% data for testing, 80% for training
    random_state=42     # ensures same split every time (reproducibility)
)

In [14]:
# Import Logistic Regression model
from sklearn.linear_model import LogisticRegression

# Create model object
model = LogisticRegression()

# Train (fit) the model using training data
model.fit(X_train, y_train)

LogisticRegression()

In [15]:
# Make predictions on test data
y_pred = model.predict(X_test)

In [16]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [17]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64

In [18]:
# Import evaluation metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [19]:
# Calculate accuracy (how many predictions are correct)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7988826815642458

In [20]:
# Confusion Matrix (actual vs predicted)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[89 16]
 [20 54]]

In [21]:

# Detailed report (precision, recall, f1-score)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [22]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
331       1    1   45      0      0    28         2      1
733       2    1   23      0      0    13         2      1
382       3    1   32      0      0     7         2      1
704       3    1   26      1      0     7         2      0
813       3    0    6      4      2    31         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
106       3    0   21      0      0     7         2      1
270       1    1   29      0      0    31         2      1
860       3    1   41      2      0    14         2      0
435       1    0   14      1      2   120         2      0
102       1    1   21      0      1    77         2      0

[712 rows x 8 columns]

In [23]:
X

     pclass  sex  age  sibsp  parch  fare  embarked  alone
0         3    1   22      1      0     7         2      0
1         1    0   38      1      0    71         0      0
2         3    0   26      0      0     7         2      1
3         1    0   35      1      0    53         2      0
4         3    1   35      0      0     8         2      1
..      ...  ...  ...    ...    ...   ...       ...    ...
886       2    1   27      0      0    13         2      1
887       1    0   19      0      0    30         2      1
888       3    0   29      1      2    23         2      0
889       1    1   26      0      0    30         0      1
890       3    1   32      0      0     7         1      1

[891 rows x 8 columns]

In [24]:
# Import StandardScaler
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [25]:
# Import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

# Create a KNN model object (e.g., with n_neighbors=5)
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train the KNN model using the scaled training data
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [26]:
# Make predictions on the scaled test data
y_pred_knn = knn_model.predict(X_test_scaled)

### KNN Model Evaluation

In [27]:
# Calculate accuracy for KNN
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print("KNN Accuracy:", accuracy_knn)

# Confusion Matrix for KNN
cm_knn = confusion_matrix(y_test, y_pred_knn)
print("\nKNN Confusion Matrix:\n", cm_knn)

# Classification Report for KNN
report_knn = classification_report(y_test, y_pred_knn)
print("\nKNN Classification Report:\n", report_knn)

KNN Accuracy: 0.7988826815642458

KNN Confusion Matrix:
 [[89 16]
 [20 54]]

KNN Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [28]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
331       1    1   45      0      0    28         2      1
733       2    1   23      0      0    13         2      1
382       3    1   32      0      0     7         2      1
704       3    1   26      1      0     7         2      0
813       3    0    6      4      2    31         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
106       3    0   21      0      0     7         2      1
270       1    1   29      0      0    31         2      1
860       3    1   41      2      0    14         2      0
435       1    0   14      1      2   120         2      0
102       1    1   21      0      1    77         2      0

[712 rows x 8 columns]

In [29]:
X_train_scaled

array([[-1.61413602,  0.7243102 ,  1.20171344, ..., -0.08024759,
         0.5635246 ,  0.81220297],
       [-0.40055118,  0.7243102 , -0.49136439, ..., -0.36900912,
         0.5635246 ,  0.81220297],
       [ 0.81303367,  0.7243102 ,  0.20125836, ..., -0.48451374,
         0.5635246 ,  0.81220297],
       ...,
       [ 0.81303367,  0.7243102 ,  0.89388111, ..., -0.34975835,
         0.5635246 , -1.23121934],
       [-1.61413602, -1.38062393, -1.18398714, ...,  1.69082316,
         0.5635246 , -1.23121934],
       [-1.61413602,  0.7243102 , -0.64528056, ...,  0.86304009,
         0.5635246 , -1.23121934]])

In [30]:
# Import Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB

# Create a Gaussian Naive Bayes model object
nb_model = GaussianNB()

# Train the Naive Bayes model using the scaled training data
nb_model.fit(X_train, y_train)

# Make predictions on the scaled test data
y_pred_nb = nb_model.predict(X_test)

# --- Naive Bayes Model Evaluation ---

# Calculate accuracy for Naive Bayes
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:", accuracy_nb)

# Confusion Matrix for Naive Bayes
cm_nb = confusion_matrix(y_test, y_pred_nb)
print("\nNaive Bayes Confusion Matrix:\n", cm_nb)

# Classification Report for Naive Bayes
report_nb = classification_report(y_test, y_pred_nb)
print("\nNaive Bayes Classification Report:\n", report_nb)

Naive Bayes Accuracy: 0.776536312849162

Naive Bayes Confusion Matrix:
 [[82 23]
 [17 57]]

Naive Bayes Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.78      0.80       105
           1       0.71      0.77      0.74        74

    accuracy                           0.78       179
   macro avg       0.77      0.78      0.77       179
weighted avg       0.78      0.78      0.78       179

#Decision tree

In [31]:
# Import Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

# Initialize the model with a fixed random state (for reproducibility)
model_DT = DecisionTreeClassifier(random_state=42)

In [32]:
# Train the model using training data
# X_train → input features
# y_train → target labels
model_DT.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [33]:
# Make predictions using the trained Decision Tree model
# X_test_scaled → test features (after scaling, if you applied scaling)
y_pred_DT = model_DT.predict(X_test_scaled)

# Display predicted values
y_pred_DT

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1])

In [34]:
accuracy_score(y_test, y_pred_DT)

0.7988826815642458

In [35]:
# Confusion Matrix for Naive Bayes
cm_nb = confusion_matrix(y_test, y_pred_nb)
print("\nDecision Tree Matrix:\n", cm_nb)

# Classification Report for Naive Bayes
report_nb = classification_report(y_test, y_pred_nb)
print("\nDecision Tree Report:\n", report_nb)

Decision Tree Matrix:
 [[82 23]
 [17 57]]

Decision Tree Report:
               precision    recall  f1-score   support

           0       0.83      0.78      0.80       105
           1       0.71      0.77      0.74        74

    accuracy                           0.78       179
   macro avg       0.77      0.78      0.77       179
weighted avg       0.78      0.78      0.78       179

#SVM

In [36]:
# Import SVM model
from sklearn.svm import SVC

# Import evaluation metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize SVM model
# kernel='rbf' is default (works well in most cases)
model_SVM = SVC(kernel='rbf', random_state=42)

# Train the model
model_SVM.fit(X_train_scaled, y_train)

# Make predictions
y_pred_SVM = model_SVM.predict(X_test_scaled)

# Display predictions
y_pred_SVM

# Calculate accuracy
acc_SVM = accuracy_score(y_test, y_pred_SVM)
print("SVM Accuracy:", acc_SVM)

# Confusion Matrix
cm_SVM = confusion_matrix(y_test, y_pred_SVM)
print("\nSVM Confusion Matrix:\n", cm_SVM)

# Classification Report
report_SVM = classification_report(y_test, y_pred_SVM)
print("\nSVM Classification Report:\n", report_SVM)

SVM Accuracy: 0.8156424581005587

SVM Confusion Matrix:
 [[92 13]
 [20 54]]

SVM Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.88      0.85       105
           1       0.81      0.73      0.77        74

    accuracy                           0.82       179
   macro avg       0.81      0.80      0.81       179
weighted avg       0.82      0.82      0.81       179

#Cross valid

In [37]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[891 rows x 9 columns]

In [38]:

# Features and target
X = df.drop('survived', axis=1)
y = df['survived']

In [39]:
# Import cross validation
from sklearn.model_selection import cross_val_score

In [40]:
scalar = StandardScaler()

In [41]:
X_scaled = scalar.fit(X)

In [44]:

# Create SVM model
model_svm = SVC()

# Correctly scale X
# X_scaled was incorrectly assigned in the previous cell (1uymwLuYyUUW).
# It should contain the transformed data, not the scaler object itself.
X_scaled = scalar.fit_transform(X)

# Cross validation
scores = cross_val_score(
    model_svm,
    X_scaled,
    y,
    cv=5,
    scoring='accuracy'
)

# Print results
print(scores)
print("Average Accuracy:", scores.mean())

[0.83240223 0.82022472 0.81460674 0.80898876 0.86516854]
Average Accuracy: 0.828278199736363