In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

In [ ]:
df = sns.load_dataset("titanic")

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.drop(["deck", "alive", "class", "who", "adult_male", "embark_town"], axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [ ]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["embarked"].fillna(df["embarked"].mode()[0], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  891 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [ ]:
# Import LabelEncoder from sklearn
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
le = LabelEncoder()

In [ ]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [ ]:
df=df.astype(int)

In [ ]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [ ]:
# Separate features (X) and target (y)

# Drop 'survived' column from dataset → this becomes input features
X = df.drop("survived", axis=1)

# Select 'survived' column → this is the target variable
y = df["survived"]


# Import function to split dataset
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,      # 20% data for testing, 80% for training
    random_state=42     # ensures same split every time (reproducibility)
)

In [ ]:
# Import Logistic Regression model
from sklearn.linear_model import LogisticRegression

# Create model object
model = LogisticRegression()

# Train (fit) the model using training data
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
# Make predictions on test data
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [ ]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64

In [ ]:
# Import evaluation metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# Calculate accuracy (how many predictions are correct)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7988826815642458

In [ ]:
# Confusion Matrix (actual vs predicted)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[89 16]
 [20 54]]

In [ ]:

# Detailed report (precision, recall, f1-score)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [ ]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
331       1    1   45      0      0    28         2      1
733       2    1   23      0      0    13         2      1
382       3    1   32      0      0     7         2      1
704       3    1   26      1      0     7         2      0
813       3    0    6      4      2    31         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
106       3    0   21      0      0     7         2      1
270       1    1   29      0      0    31         2      1
860       3    1   41      2      0    14         2      0
435       1    0   14      1      2   120         2      0
102       1    1   21      0      1    77         2      0

[712 rows x 8 columns]

In [ ]:
X

     pclass  sex  age  sibsp  parch  fare  embarked  alone
709       3    1   29      1      1    15         0      0
439       2    1   31      0      0    10         2      1
840       3    1   20      0      0     7         2      1
720       2    0    6      0      1    33         2      0
39        3    0   14      1      0    11         0      0
..      ...  ...  ...    ...    ...   ...       ...    ...
433       3    1   17      0      0     7         2      1
773       3    1   29      0      0     7         0      1
25        3    0   38      1      5    31         2      0
84        2    0   17      0      0    10         2      1
10        3    0    4      1      1    16         2      0

[179 rows x 8 columns]

In [ ]:
# Import StandardScaler
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

# Create a KNN model object (e.g., with n_neighbors=5)
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train the KNN model using the scaled training data
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [ ]:
# Make predictions on the scaled test data
y_pred_knn = knn_model.predict(X_test_scaled)

### KNN Model Evaluation

In [ ]:
# Calculate accuracy for KNN
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print("KNN Accuracy:", accuracy_knn)

# Confusion Matrix for KNN
cm_knn = confusion_matrix(y_test, y_pred_knn)
print("\nKNN Confusion Matrix:\n", cm_knn)

# Classification Report for KNN
report_knn = classification_report(y_test, y_pred_knn)
print("\nKNN Classification Report:\n", report_knn)

KNN Accuracy: 0.7988826815642458

KNN Confusion Matrix:
 [[89 16]
 [20 54]]

KNN Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.85      0.83       105
           1       0.77      0.73      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [ ]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
331       1    1   45      0      0    28         2      1
733       2    1   23      0      0    13         2      1
382       3    1   32      0      0     7         2      1
704       3    1   26      1      0     7         2      0
813       3    0    6      4      2    31         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
106       3    0   21      0      0     7         2      1
270       1    1   29      0      0    31         2      1
860       3    1   41      2      0    14         2      0
435       1    0   14      1      2   120         2      0
102       1    1   21      0      1    77         2      0

[712 rows x 8 columns]

In [ ]:
X_train_scaled

array([[-1.61413602,  0.7243102 ,  1.20171344, ..., -0.08024759,
         0.5635246 ,  0.81220297],
       [-0.40055118,  0.7243102 , -0.49136439, ..., -0.36900912,
         0.5635246 ,  0.81220297],
       [ 0.81303367,  0.7243102 ,  0.20125836, ..., -0.48451374,
         0.5635246 ,  0.81220297],
       ...,
       [ 0.81303367,  0.7243102 ,  0.89388111, ..., -0.34975835,
         0.5635246 , -1.23121934],
       [-1.61413602, -1.38062393, -1.18398714, ...,  1.69082316,
         0.5635246 , -1.23121934],
       [-1.61413602,  0.7243102 , -0.64528056, ...,  0.86304009,
         0.5635246 , -1.23121934]])

In [ ]:
# Import Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB

# Create a Gaussian Naive Bayes model object
nb_model = GaussianNB()

# Train the Naive Bayes model using the scaled training data
nb_model.fit(X_train, y_train)

# Make predictions on the scaled test data
y_pred_nb = nb_model.predict(X_test)

# --- Naive Bayes Model Evaluation ---

# Calculate accuracy for Naive Bayes
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:", accuracy_nb)

# Confusion Matrix for Naive Bayes
cm_nb = confusion_matrix(y_test, y_pred_nb)
print("\nNaive Bayes Confusion Matrix:\n", cm_nb)

# Classification Report for Naive Bayes
report_nb = classification_report(y_test, y_pred_nb)
print("\nNaive Bayes Classification Report:\n", report_nb)

Naive Bayes Accuracy: 0.776536312849162

Naive Bayes Confusion Matrix:
 [[82 23]
 [17 57]]

Naive Bayes Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.78      0.80       105
           1       0.71      0.77      0.74        74

    accuracy                           0.78       179
   macro avg       0.77      0.78      0.77       179
weighted avg       0.78      0.78      0.78       179